git:
  overrideGpg: true
  log:
    showWholeGraph: false
  diffRenderers:
    - command: delta --dark --paging=never --line-numbers
    - command: delta --dark --paging=never --line-numbers --side-by-side
